### PR TITLE
Added support std::array

### PR DESCRIPTION
**Pull request by philipp-classen**
Refers to pull request: https://github.com/grogers0/CppQuickCheck/pull/5

### CODE REVIEW

**Comment by rpietruc** [comment]
Hi,
In order to compile with my C++03 project I needed to change line 1162 of Generator.h to:
for (auto shrinkedInnerElem : m_gen.shrink(arr[i])) {
was:
for (auto &shrinkedInnerElem : m_gen.shrink(arr[i])) {

**Comment by philipp-classen** [comment]
@rpietruc I can change the line but it would be good to understand why it fails. What compiler do you use and what error do you get?

The good looks OK, and at least the examples build fine with clang 3.6 and GCC 5.

**Comment by rpietruc** [comment]
gcc version 4.9.2 20150304 (prerelease) (GCC)
In file included from /usr/include/cppqc.h:4:0,
                 from main.cpp:2:
/usr/include/cppqc/Generator.h: In instantiation of 'std::vector<std::array<_Tp, _Nm> > cppqc::detail::ArrayOfStatelessGenerator<T, N>::shrink(const std::array<_Tp, _Nm>&) const [with T = bool; long unsigned int N = 20ul]':
/usr/include/cppqc/Generator.h:170:42:   required from 'std::vector<_RealType> cppqc::StatelessGenerator<T>::StatelessGenModel<StatelessGeneratorModel>::shrink(const T&) [with StatelessGeneratorModel = cppqc::detail::ArrayOfStatelessGenerator<bool, 20ul>; T = std::array<bool, 20ul>]'
../../../include/robots/rtrccrc.h:21:23:   required from here
/usr/include/cppqc/Generator.h:1162:21: error: invalid initialization of non-const reference of type 'std::_Bit_reference&' from an rvalue of type 'std::_Bit_iterator::reference {aka std::_Bit_reference}'
                     for (auto &shrinkedInnerElem : m_gen.shrink(arr[i])) {
                     ^
/usr/include/cppqc/Generator.h: In instantiation of 'std::vector<std::array<_Tp, _Nm> > cppqc::detail::ArrayOfStatelessGenerator<T, N>::shrink(const std::array<_Tp, _Nm>&) const [with T = bool; long unsigned int N = 7ul]':
/usr/include/cppqc/Generator.h:170:42:   required from 'std::vector<_RealType> cppqc::StatelessGenerator<T>::StatelessGenModel<StatelessGeneratorModel>::shrink(const T&) [with StatelessGeneratorModel = cppqc::detail::ArrayOfStatelessGenerator<bool, 7ul>; T = std::array<bool, 7ul>]'
../../../include/robots/rtrccrc.h:21:23:   required from here
/usr/include/cppqc/Generator.h:1162:21: error: invalid initialization of non-const reference of type 'std::_Bit_reference&' from an rvalue of type 'std::_Bit_iterator::reference {aka std::_Bit_reference}'
Makefile:648: recipe for target 'main.o' failed

**Comment by rpietruc** [comment]
for (const auto &shrinkedInnerElem : m_gen.shrink(arr[i])) {
- (with const) works also fine for me

**Comment by philipp-classen** [comment]
@rpietruc  Thanks a lot. I was able to reproduce it.
It is fixed now.
